apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: cs693
  labels:
    app: api
spec:
  replicas: 1
  selector:
    # This must match the labels we set on the pod
    matchLabels:
      app: api
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: api
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '80'
    spec:
      volumes:
      - name: credentials-secret
        secret:
          secretName: credentials
      containers:
      - name: api
        imagePullPolicy: Always
        image: 190601597280.dkr.ecr.us-east-1.amazonaws.com/asav-eks-test:api
        env:
        - name: APP_ENV
          value: "local"
        volumeMounts:
        - name: credentials-secret
          mountPath: /etc/secrets/credentials
          readOnly: true
        command: ["./startup.sh"]
