apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: cs693
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: webapp
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: cs693
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80  # Container port
  selector:
    app: api