apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: cs693
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    # This must match the labels we set on the pod
    matchLabels:
      app: webapp
  template:
    metadata:
      # Set labels on the pod.
      # This is used in the deployment selector.
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        imagePullPolicy: Always
        image: 190601597280.dkr.ecr.us-east-1.amazonaws.com/asav-eks-test:webapp
        env:
        - name: APP_ENV
          value: "local"